---
- name: Remove Kubernetes resources with label env=webapp
  hosts: localhost
  gather_facts: no
  tasks:


  
    - name: Search for all Pods labelled app=web
      kubernetes.core.k8s_info:
        kind: Service
        label_selectors:
           - pupose = demo
      register: k8s_result

    - debug:
        msg: "{{ k8s_result }}"
           
    - name: Remove Kubernetes services with label purpose=demo
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Service
        label_selectors: 
           - purpose = demo
        namespace: openshift-cnv

    - name: Remove Kubernetes routes with label purpose=demo
      kubernetes.core.k8s:
        state: absent
        api_version: route.openshift.io/v1
        kind: Route
        label_selectors: 
           - purpose = demo
        namespace: openshift-cnv


    - name: Remove Kubernetes VirtualMachineInstance with label purpose=demo
      kubernetes.core.k8s:
        state: absent
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        label_selectors: 
           - purpose = demo
        namespace: openshift-cnv

