
---
- name: Provision OCP-CNV Report Server and Create Necessary Service and Route
  hosts: localhost
  
  # Paste lines 9-14 in Controller Extra Vars or uncomment here
  # For demos that require a report server, ensure that report_server: openshift-cnv-report is defined in extra vars
  # vars:
  #   vm_name: report
  #   vm_namespace: openshift-cnv
  #   os_version: rhel9
  #   cloudusername: null
  #   cloudpassword: null
  #   ssh_authorized_key: null
  #   rh_ak: null
  #   rh_org_id: null
    
  tasks:
    - name: Define resources
      kubernetes.core.k8s:
        wait: true
        state: "{{ instance_state | default('present') }}"
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_namespace }}"
            labels:
              purpose: report
              app: "{{ vm_name }}"
              os.template.kubevirt.io/fedora36: 'true'
              vm.kubevirt.io/name: "{{ vm_name }}"
          spec:
            dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  creationTimestamp: null
                  name: "{{ vm_name }}"
                  labels:
                    purpose: 'report'
                spec:
                  sourceRef:
                    kind: DataSource
                    name: "{{ os_version }}"
                    namespace: openshift-virtualization-os-images
                  storage:
                    resources:
                      requests:
                        storage: 30Gi
            running: true
            template:
              metadata:
                annotations:
                  vm.kubevirt.io/flavor: small
                  vm.kubevirt.io/os: "{{ os_version }}"
                  vm.kubevirt.io/workload: server
                creationTimestamp: null
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
                  kubevirt.io/size: small
                  env: report
                  purpose: report
              spec:
                domain:
                  cpu:
                    cores: 4
                    sockets: 1
                    threads: 1
                  devices:
                    disks:
                      - disk:
                          bus: virtio
                        name: rootdisk
                      - disk:
                          bus: virtio
                        name: cloudinitdisk
                    interfaces:
                      - masquerade: {}
                        model: virtio
                        name: default
                    networkInterfaceMultiqueue: true
                    rng: {}
                  machine:
                    type: pc-q35-rhel9.2.0
                  resources:
                    requests:
                      memory: 8Gi
                evictionStrategy: LiveMigrate
                networks:
                  - name: default
                    pod: {}
                terminationGracePeriodSeconds: 180
                volumes:
                  - dataVolume:
                      name: "{{ vm_name }}"
                    name: rootdisk
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      userData: |-
                        #cloud-config
                        user: "{{ cloudusername }}"
                        password: "{{ cloudpassword }}"
                        chpasswd: { expire: False }
                        ssh_pwauth: True
                        ssh_authorized_keys:
                            - "{{ ssh_authorized_key }}"
      delegate_to: localhost
      
    - name: Create webapp service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: report
            namespace: openshift-cnv
            labels:
              purpose: report
          spec:
            selector:
              env: report
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create webapp route
      kubernetes.core.k8s:
        state: present
        definition: 
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            name: report
            namespace: openshift-cnv
            labels:
              purpose: report
          spec:
            to:
              kind: Service
              name: report
            tls: null
            port:
              targetPort: 80
      delegate_to: localhost

  # Normally we could wait for SSH to be up and running, however,
  # we don't know the IP address (or have name resolution) of the VM
  # until after the inventory sync occurs
    - name: Sleep for 300 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 100
      delegate_to: localhost

    - name: Refresh OpenShift CNV Inventory Source
      ansible.awx.awx:
         name: "OpenShift CNV Inventory" 
         inventory: "Demo Inventory"
         organization: Default
      delegate_to: localhost

- name: Configure Report Server VM
  hosts: openshift-cnv-{{ vm_name }}
  become: true
  tasks:

    - name: Register and subscribe RHEL system
      redhat_subscription:
        state: present
        activationkey: "{{ rh_ak }}"
        org_id: "{{ rh_org_id }}"
   
  

  
  
  

   
       

      


