- name: Create Service and Route for our Apache Webserver
  hosts: localhost

  tasks:
    - name: Create webapp service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: webapp
            namespace: openshift-cnv
            labels:
              purpose: demo
          spec:
            selector:
              env: webapp
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create webapp route
      kubernetes.core.k8s:
        state: present
        definition: 
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            name: webapp
            namespace: openshift-cnv
            labels:
              purpose: demo
          spec:
            to:
              kind: Service
              name: webapp
            tls: null
            port:
              targetPort: 80

